# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  displayName: 'Code build'
  inputs:
    mavenPomFile: 'azure-poc/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'
- task: CopyFiles@2
  displayName: 'Copy jar file'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
- task: AmazonWebServices.aws-vsts-tools.LambdaDeployFunction.LambdaDeployFunction@1
  displayName: 'Deploy on Lambda Function'
  inputs:
    awsCredentials: 'azure-lambda-push-connection'
    regionName: 'ap-south-1'
    functionName: 'arn:aws:lambda:ap-south-1:423181991362:function:poc-azure-devops-lambda'
    localZipFile: '$(build.artifactstagingdirectory)/azure-poc/target/azure.poc.microservice.jar'
	condition: succeededOrFailed()